### ISSUE TITLE
Can't edit time schedule after update

### ISSUE THREAD

**Issue by dfares1987** [niklaswall/node-red-contrib-light-scheduler#52]
Hi i update my node-red do version 1.1.0 and node.js to v12.18.2 since that i can edit time schedule

**Comment by niklaswall** [comment]
Ok, I will do some testing!

**Comment by jplivingston08** [comment]
Same issue for me as well. Thanks.

**Comment by sehekuwe** [comment]
Same issue as well, just updated to node red 1.1.0.  Thank you for looking into this.

**Comment by casperse** [comment]
Yes same issue here cant "select" or "Draw" the ON/OFF in the scheduler anymore (HA Node-red 7.0) and latest Light scheduler (This is the greatest plugin in Node-rad Thanks!)

**Comment by mbedworth** [comment]
I have this issue as well

**Comment by veno77** [comment]
same issue with me after upgrade HA node-red to 7.0

**Comment by amvesa** [comment]
I just started with HA/Node-Red in the past couple weeks but I am on v7. Attempting my first use of the schedulers I am also unable to configure times.

**Comment by DarKOrange75** [comment]
Same issue here, I can't update the schedule anymore. I am running Node Red in home assistant and version is 1.1.0

**Comment by xbonnaire** [comment]
Hi, same issue for me. I've just upgraded the Node-Red to version 7 in Home Assistant, and I am unable to configure times (unable to select). Moreover, when nothing seems selected, the output is set to ON. It appears that my previous configuration had the actual schedule period to ON, but it does not show on the timetable, and it is impossible to edit.

**Comment by adizag** [comment]
+1

**Comment by baccula** [comment]
Same issue here, using Node-RED add-on in HomeAssistantOS.

**Comment by xbonnaire** [comment]
> Ok, I will do some testing!

If it can help, here the video of the node configuration behavior on my update version of Node-Red for Home Assistant (this is with Chrome browser, but using Firefox does the same thing).

[https://youtu.be/LTWDoKBjrt4](https://youtu.be/LTWDoKBjrt4)

**Comment by mickym2** [comment]
For me the same - since update from nodeRed version 1.0.2 to 1.1.2 - I am no longer able to do some changes in the GUI to schedule. It is not related to th browser. I tested on Chrome and Edge.

**Comment by xbonnaire** [comment]
> For me the same - since update from nodeRed version 1.0.2 to 1.1.2 - I am no longer able to do some changes in the GUI to change or modify the schedule. It is not related to th browser. I tested on Chrome and Edge. It would be great - if this will work again, as I love these nodes. ;)

For me it is the best scheduler for Node-Red. I use it for heating schedules (not for light :-) ). Changing my settings using another nodes would really be a pain.

**Comment by niklaswall** [comment]
It looks like the problem is related to this error message:
`[Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

In that case, serving the node-red UI over HTTPS should solve the problem (not tested). How that is done is descibed here: https://nodered.org/docs/user-guide/runtime/securing-node-red#enabling-https-access

**Comment by mickym2** [comment]
But this was not in my error log. So I guees the problem ist with DevTools.

**Comment by niklaswall** [comment]
After some research there seam to be multiple issues that hides behind this issue.
One of them might be related to HA specific situations (The HTTPS issue I mentioned above)

**Comment by niklaswall** [comment]
I just published V0.0.16 that should fix the editing issue. At least it now works on my main installation.

Please let me know how this works for you!

**Comment by adizag** [comment]
I'm working with hassio and node red is an addon of HASSIO.
My HASSIO is https secured, so how can that be solved?

בתאריך יום ב׳, 13 ביולי 2020, 14:45, מאת Niklas Wall ‏<
notifications@github.com>:

**Comment by xbonnaire** [comment]
> I just published V0.0.16 that should fix the editing issue. At least it now works on my main installation.
> 
> Please let me know how this works for you!

Hi, it seems that it does not solve the problem for me. To be sure, can you publish the update so that the new version will be available to the Node-Red "Manage Palette" tab?

**I now have the following errors in the JavaScript console:**
vendor.js:4 JQMIGRATE: Migrate is installed, version 3.3.0
DevTools failed to load SourceMap: Could not load content for http://192.168.1.32:8123/api/hassio_ingress/2kpd8wopYCJDUobJ-OxNym8s8rFjuMxdhAoU1VkRXoo/vendor/purify.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
red.min.js:16 Node-RED: 1.1.0
red.min.js:16 Versions
red.min.js:16 jQuery 3.5.1
red.min.js:16 jQuery UI 1.12.1
red.min.js:16 ACE 1.4.3
red.min.js:16 D3 3.0.3
red.min.js:16 Projects disabled
2DevTools failed to load SourceMap: Could not load content for http://192.168.1.32:8123/gridstack.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM678:formatted:2808 Uncaught TypeError: Cannot read property 'event' of undefined
    at HTMLDivElement.<anonymous> (<anonymous>:7:22874)
    at Function.each (vendor.js:2)
    at s.fn.init.each (vendor.js:2)
    at Et.e.constructor.renderFgSegEls (<anonymous>:7:22823)
    at Et.e.constructor.renderFgSegsIntoContainers (<anonymous>:8:26181)
    at Et.e.constructor.renderFgSegs (<anonymous>:8:24463)
    at Et.e.constructor.renderFgEvents (<anonymous>:7:22441)
    at Et.e.constructor.renderEvents (<anonymous>:7:22269)
    at Et.e.constructor.renderEvents (<anonymous>:10:12003)
    at Et.e.constructor.executeEventsRender (<anonymous>:9:5168)
(anonymous) @ VM678:formatted:1793
each @ vendor.js:2
each @ vendor.js:2
renderFgSegEls @ VM678:formatted:1793
renderFgSegsIntoContainers @ VM678:formatted:3169
renderFgSegs @ VM678:formatted:3169
renderFgEvents @ VM678:formatted:1793
renderEvents @ VM678:formatted:1793
renderEvents @ VM678:formatted:5771
executeEventsRender @ VM678:formatted:4453
(anonymous) @ VM678:formatted:4453
runTaskFunc @ VM678:formatted:6
runTask @ VM678:formatted:6
runNext @ VM678:formatted:6
e @ VM678:formatted:6
runTaskFunc @ VM678:formatted:6
runTask @ VM678:formatted:6
runNext @ VM678:formatted:6
tryStart @ VM678:formatted:6
resume @ VM678:formatted:6
stopBatchRender @ VM678:formatted:3169
resetEvents @ VM678:formatted:4453
i @ vendor.js:2
n @ VM678:formatted:6
dispatch @ vendor.js:2
v.handle @ vendor.js:2
trigger @ vendor.js:2
triggerHandler @ vendor.js:2
trigger @ VM678:formatted:1793
i @ VM678:formatted:6
M @ VM678:formatted:6
k @ VM678:formatted:6
(anonymous) @ VM678:formatted:6
each @ vendor.js:2
each @ vendor.js:2
t.fn.fullCalendar @ VM678:formatted:6
select @ VM575:114
publiclyTrigger @ VM678:formatted:4453
publiclyTrigger @ VM678:formatted:3169
triggerSelect @ VM678:formatted:4453
reportSelection @ VM678:formatted:4453
interactionEnd @ VM678:formatted:1793
trigger @ VM678:formatted:1793
handleInteractionEnd @ VM678:formatted:1793
handleInteractionEnd @ VM678:formatted:1793
endInteraction @ VM678:formatted:1793
i @ vendor.js:2
n @ VM678:formatted:6
dispatch @ vendor.js:2
v.handle @ vendor.js:2
trigger @ vendor.js:2
triggerHandler @ vendor.js:2
trigger @ VM678:formatted:1793
handleMouseUp @ VM678:formatted:1793
i @ vendor.js:2
dispatch @ vendor.js:2
v.handle @ vendor.js:2

**If it can help:**

The two DevTools errors appear at the first load of the Node-Red tab in the browser (Chrome). The HTTPS complaint has disappeared. The other error appears when you try to add an event in the Light Scheduler calendar.

All the errors @VM678 come from the FullCalendar v3.4.0 code.

**Comment by dfares1987** [comment]
problem solved just update the package with npm

**Comment by xbonnaire** [comment]
> problem solved just update the package with npm

I have no way to install the package with npm on Home Assistant (Docker run). It must be installed using the Node-Red Mange Palette option. And at this time this is still  version 0.0.15 which is available, not 0.0.16.

I have manually copied the new files to my Node-Red light scheduler directory, but the problem persists for me (see above JavaScript console errors).

**Comment by xbonnaire** [comment]
Ok, I've found in the HA Node-Red add-on configuration how to make it load some packages from npmjs when the add-on starts.
I now have a correct installation of the 0.016 version which effectively solves the problem of the calendar :-) 

Thanks to @niklaswall for his fast correction of this issue :-) This will prevent me from using 70 Bigtimer nodes to do the same thing.

**Comment by knolleary** [comment]
@dfares1987 fyi, the flow library no longer automatically detects updates to published modules - you have to go to its page on the flow library, login with the GitHub link in the top right corner and then click the 'request refresh' link in the sidebar.

I have done so for this module and 0.0.16 is now listed on the site.

**Comment by niklaswall** [comment]
Thanks @knolleary! 

I didn't know that :-(

//Niklas

**Comment by mickym2** [comment]
Many thanks to Niklas from my side. The update worked for me as well. :)

**Comment by adizag** [comment]
FIXED! thanks!!


____________________________________________
"יש המטביעים את צרותיהם - ויש המלמדים אותן לשחות..."
"אין מקום שהוא רחוק מדי"
